### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by floforsthuber** [JuliaDiffinDiffs/InteractionWeightedDIDs.jl#17]
Dear Norman,
I wanted to try out your DiD package, but I could not find any documentation on the commands, could you point me towards something? Hope this is okay to post here.
Best, Florian

**Comment by junyuan-chen** [comment]
Hi Florian,

A tutorial-style documentation is still not available right now, although docstrings should be reasonably complete.
To get some sense on how things work, you might want to take a look at how `@did` is used in the test file [here](https://github.com/JuliaDiffinDiffs/InteractionWeightedDIDs.jl/blob/master/test/did.jl).

The `@did` macro is where all the specifications are entered. Its first argument should be `Reg` and you can use the help mode in Julia REPL to see the arguments accepted by typing `?RegressionBasedDID`.

There are some details such as the specification for treatment timing that needs extra clarification. A documentation that explains the usage with examples is something that will be added at some point of time once I get back to work on it.
